### ISSUE TITLE
Change to returning an "Entity" object rather than json_doc?

### ISSUE THREAD

**Issue by vinay0000** [ptgrogan/tat-c-architecture-demo#1]
https://github.com/ptgrogan/tat-c-architecture-demo/blob/f60091870fed0a832aa846f889f7a77db6da3874/tatc/util.py#L82

**Comment by ptgrogan** [comment]
The if-condition above checks if json_doc is already null (None), a recognized primitive (Number), or an Entity. In these three conditions, json_doc is returned directly. This functionality allows from_json to be called recursively without ill-effects if a portion of the json_doc is already parsed into Python objects.

**Comment by vinay0000** [comment]
Okay, in my workspace I had tried the following (condensed version): 

`class FieldOfView(Entity):
 
       def __init__(self, geometry = None,  _id = None):
            self.geometry = geometry
            super(FieldOfView, self).__init__(_id, "FieldOfView")

        @staticmethod
        def from_dict(d):
            return FieldOfView( d.get("geometry", None), d.get("_id", None))`

In tested for `FieldOfView.from_json({"geometry": "Cone"})`, which works as expected.

For `FieldOfView.from_json(2)` (not a correct json formatted input), the output is just the number '2'. I would have expected an error message (saying incorrect json format) or an Empty object of the type `FieldOfView`.
